# Generated by Django 5.0.1 on 2024-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
