# Generated by Django 5.0.1 on 2024-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Почтовый индекс')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заказа')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.PositiveIntegerField(default=1, verbose_name='Кол-во товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
